// <auto-generated />
using System;
using FeriadosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeriadosAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220315035649_01CreateDb")]
    partial class _01CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeriadosAPI.Models.FeriadoEstadual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixoMovel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("APIFeriadoEstadual");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(1900, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Revolução Constitucionalista de 1932",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(1900, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Dia de São Jorge",
                            Uf = "RJ"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(1900, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Dia da Consciência Negra",
                            Uf = "RJ"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(1900, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Data Magna de Minas Gerais",
                            Uf = "MG"
                        });
                });

            modelBuilder.Entity("FeriadosAPI.Models.FeriadoMunicipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixoMovel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("APIFeriadoMunicipal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Guarulhos",
                            Data = new DateTime(1900, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Aniversário de Guarulhos",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "São Paulo",
                            Data = new DateTime(1900, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Aniversário de São Paulo",
                            Uf = "SP"
                        });
                });

            modelBuilder.Entity("FeriadosAPI.Models.FeriadoNacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixoMovel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("APIFeriadoNacional");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Confraternização Universal"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(1900, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Tiradentes"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(1900, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Dia do Trabalhador"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(1900, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Independência"
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(1900, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Nossa Senhora Aparecida"
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(1900, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Finados"
                        },
                        new
                        {
                            Id = 7,
                            Data = new DateTime(1900, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Proclamação da República"
                        },
                        new
                        {
                            Id = 8,
                            Data = new DateTime(1900, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FixoMovel = "F",
                            Nome = "Natal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
